apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1337
      protocol: TCP
      name: "1337"
  selector:
    {{- include "strapi.selectorLabels" . | nindent 4 }}
